### ISSUE TITLE
[on hold] add ability to run as a CI check

### ISSUE THREAD

**Issue by Bullrich** [paritytech/license-scanner#20]
Add the ability to make this project work as a CI check, possibly as a GitHub action.

- [x] polkadot -> https://github.com/paritytech/polkadot/pull/6609
- [ ] substrate
- [ ] cumulus

**Comment by rzadp** [comment]
On hold because of the monorepo efforts on the way.

**Comment by kianenigma** [comment]
We do run the license-checker in CI as far as I can say: https://github.com/paritytech/polkadot-sdk/blob/master/.github/workflows/check-licenses.yml

**Comment by mordamax** [comment]
@kianenigma thx it's old issue, after migration to monorepo we should've closed this one
