### ISSUE TITLE
Optimization idea: Skip scanning files if their checksum doesn't change

### ISSUE THREAD

**Issue by joao-paulo-parity** [paritytech/license-scanner#7]
Before scanning a file the script could compute its checksum and check if its database entry has the same checksum. If that's true, the scanning can be skipped for that file under the assumption that it will result in the same verdict because the contents' checksum did not change.

It's relevant to consider if this optimization results in significant performance improvements for our workloads as relying on assumptions adds more uncertainty risk to the verdicts.

**Comment by mordamax** [comment]
Won't do
