### ISSUE TITLE
[polkadot/ci] add ci license check to polkadot repo

### ISSUE THREAD

**Issue by drahnr** [paritytech/license-scanner#8]
Currently we require that a GPLv3 license header is included in every source file.

This is a rather mundane thing and should preferably be caught by CI rather than human review.

It would be nice to add this feature for polkadot.

Caveats: 

Not sure if want to include them in ui tests for proc macros, it's only glue and usually less than 10 loc.
`ui/`

**Comment by mordamax** [comment]
@rzadp this can be closed, right?

**Comment by rzadp** [comment]
Yes, closing.
